# Generated by Django 5.1.1 on 2024-09-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data_app', '0002_alter_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='client_data_app.curator'),
        ),
    ]
