# Generated by Django 5.1.1 on 2024-09-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_data_app', '0004_homework_created_at_homework_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
